"""add_user_profile_fields_and_track_indices

Revision ID: 2656e2e08e67
Revises: 9458e90618c6
Create Date: 2026-05-20 16:51:25.063953

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2656e2e08e67"
down_revision: Union[str, Sequence[str], None] = "9458e90618c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tracks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tracks_published_date"), ["published_date"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_tracks_rank"), ["rank"], unique=False)

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("username", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "is_profile_public",
                sa.Boolean(),
                server_default="false",
                nullable=False,
            )
        )
        batch_op.create_index(
            batch_op.f("ix_users_username"), ["username"], unique=True
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_column("is_profile_public")
        batch_op.drop_column("username")

    with op.batch_alter_table("tracks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tracks_rank"))
        batch_op.drop_index(batch_op.f("ix_tracks_published_date"))
    # ### end Alembic commands ###
