"""Add user_id to Playlist and Rating models

Revision ID: 85da05ac7e86
Revises: 11e1a73e6bc4
Create Date: 2026-02-12 20:40:18.513794

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "85da05ac7e86"
down_revision: Union[str, Sequence[str], None] = "11e1a73e6bc4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("playlists", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_playlists_user_id", "users", ["user_id"], ["id"]
        )

    with op.batch_alter_table("ratings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_ratings_user_id", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ratings", schema=None) as batch_op:
        batch_op.drop_constraint("fk_ratings_user_id", type_="foreignkey")
        batch_op.drop_column("user_id")

    with op.batch_alter_table("playlists", schema=None) as batch_op:
        batch_op.drop_constraint("fk_playlists_user_id", type_="foreignkey")
        batch_op.drop_column("user_id")
    # ### end Alembic commands ###
