"""Add user_id to Playlist and Rating models

Revision ID: 85da05ac7e86
Revises: 11e1a73e6bc4
Create Date: 2026-02-12 20:40:18.513794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85da05ac7e86'
down_revision: Union[str, Sequence[str], None] = '11e1a73e6bc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'playlists', 'users', ['user_id'], ['id'])
    op.add_column('ratings', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ratings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_column('ratings', 'user_id')
    op.drop_constraint(None, 'playlists', type_='foreignkey')
    op.drop_column('playlists', 'user_id')
    # ### end Alembic commands ###
