"""add_lyrics_table

Revision ID: 93a54e5e3a3d
Revises: 39fc4d34a963
Create Date: 2026-02-13 17:01:47.029834

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "93a54e5e3a3d"
down_revision: Union[str, Sequence[str], None] = "39fc4d34a963"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lyrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("translation_type", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("content", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lyrics", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_lyrics_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_lyrics_track_id"), ["track_id"], unique=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lyrics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lyrics_track_id"))
        batch_op.drop_index(batch_op.f("ix_lyrics_id"))

    op.drop_table("lyrics")
    # ### end Alembic commands ###
