"""normalize_producers_and_voicebanks

Revision ID: 9458e90618c6
Revises: 7d4f8c9a1b2e
Create Date: 2026-05-14 11:07:18.050227

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm as sa_orm


# revision identifiers, used by Alembic.
revision: str = "9458e90618c6"
down_revision: Union[str, Sequence[str], None] = "7d4f8c9a1b2e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema and migrate data."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "producers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("name_jp", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_producers_id"), "producers", ["id"], unique=False)
    op.create_index(op.f("ix_producers_name"), "producers", ["name"], unique=True)
    op.create_table(
        "voicebanks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("name_jp", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_voicebanks_id"), "voicebanks", ["id"], unique=False)
    op.create_index(op.f("ix_voicebanks_name"), "voicebanks", ["name"], unique=True)
    op.create_table(
        "track_producers",
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("producer_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["producer_id"],
            ["producers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
        ),
        sa.PrimaryKeyConstraint("track_id", "producer_id"),
    )
    op.create_table(
        "track_voicebanks",
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("voicebank_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["voicebank_id"],
            ["voicebanks.id"],
        ),
        sa.PrimaryKeyConstraint("track_id", "voicebank_id"),
    )
    op.drop_index(op.f("ix_playlists_user_id"), table_name="playlists")
    op.drop_index(op.f("ix_ratings_user_id"), table_name="ratings")
    # ### end Alembic commands ###

    # --- Data Migration ---
    bind = op.get_bind()
    session = sa_orm.Session(bind=bind)

    # Reflect tables to use them for DML
    metadata = sa.MetaData()
    tracks_t = sa.Table("tracks", metadata, autoload_with=bind)
    producers_t = sa.Table("producers", metadata, autoload_with=bind)
    voicebanks_t = sa.Table("voicebanks", metadata, autoload_with=bind)
    track_producers_t = sa.Table("track_producers", metadata, autoload_with=bind)
    track_voicebanks_t = sa.Table("track_voicebanks", metadata, autoload_with=bind)

    tracks = session.execute(sa.select(tracks_t)).all()

    producer_map = {}  # name -> id
    voicebank_map = {}  # name -> id

    for track in tracks:
        # Migrate Producers
        if track.producer:
            p_names = [p.strip() for p in track.producer.split(",")]
            p_names_jp = (
                [p.strip() for p in track.producer_jp.split(",")]
                if track.producer_jp
                else []
            )

            for i, name in enumerate(p_names):
                if not name:
                    continue
                if name not in producer_map:
                    name_jp = p_names_jp[i] if i < len(p_names_jp) else None
                    # Use connection to avoid session state issues during DDL/DML mix
                    res = bind.execute(
                        sa.insert(producers_t)
                        .values(name=name, name_jp=name_jp)
                        .returning(producers_t.c.id)
                    )
                    producer_map[name] = res.scalar()

                bind.execute(
                    sa.insert(track_producers_t).values(
                        track_id=track.id, producer_id=producer_map[name]
                    )
                )

        # Migrate Voicebanks
        if track.voicebank:
            v_names = [v.strip() for v in track.voicebank.split(",")]
            v_names_jp = (
                [v.strip() for v in track.voicebank_jp.split(",")]
                if track.voicebank_jp
                else []
            )

            for i, name in enumerate(v_names):
                if not name:
                    continue
                if name not in voicebank_map:
                    name_jp = v_names_jp[i] if i < len(v_names_jp) else None
                    res = bind.execute(
                        sa.insert(voicebanks_t)
                        .values(name=name, name_jp=name_jp)
                        .returning(voicebanks_t.c.id)
                    )
                    voicebank_map[name] = res.scalar()

                bind.execute(
                    sa.insert(track_voicebanks_t).values(
                        track_id=track.id, voicebank_id=voicebank_map[name]
                    )
                )

    session.commit()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_ratings_user_id"), "ratings", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_playlists_user_id"), "playlists", ["user_id"], unique=False
    )
    op.drop_table("track_voicebanks")
    op.drop_table("track_producers")
    op.drop_index(op.f("ix_voicebanks_name"), table_name="voicebanks")
    op.drop_index(op.f("ix_voicebanks_id"), table_name="voicebanks")
    op.drop_table("voicebanks")
    op.drop_index(op.f("ix_producers_name"), table_name="producers")
    op.drop_index(op.f("ix_producers_id"), table_name="producers")
    op.drop_table("producers")
    # ### end Alembic commands ###
