"""add_rank_history_table

Revision ID: c02033ae2a24
Revises: 2656e2e08e67
Create Date: 2026-06-02 13:42:03.580316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c02033ae2a24'
down_revision: Union[str, Sequence[str], None] = '2656e2e08e67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rank_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rank_history_id'), 'rank_history', ['id'], unique=False)
    op.create_index(op.f('ix_rank_history_rank'), 'rank_history', ['rank'], unique=False)
    op.create_index(op.f('ix_rank_history_recorded_at'), 'rank_history', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_rank_history_track_id'), 'rank_history', ['track_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rank_history_track_id'), table_name='rank_history')
    op.drop_index(op.f('ix_rank_history_recorded_at'), table_name='rank_history')
    op.drop_index(op.f('ix_rank_history_rank'), table_name='rank_history')
    op.drop_index(op.f('ix_rank_history_id'), table_name='rank_history')
    op.drop_table('rank_history')
    # ### end Alembic commands ###
