"""Initial migration

Revision ID: c0fbda4e4615
Revises:
Create Date: 2025-11-08 22:24:17.492251

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = "c0fbda4e4615"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = inspect(bind)
    tables = inspector.get_table_names()

    if "playlists" not in tables:
        op.create_table(
            "playlists",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("name", sa.String(length=100), nullable=False),
            sa.Column("description", sa.String(length=500), nullable=True),
            sa.Column("is_public", sa.Boolean(), nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )

    if "tracks" not in tables:
        op.create_table(
            "tracks",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("title", sa.String(), nullable=False),
            sa.Column("producer", sa.String(), nullable=False),
            sa.Column("voicebank", sa.String(), nullable=False),
            sa.Column("published_date", sa.DateTime(), nullable=False),
            sa.Column("link", sa.String(), nullable=False),
            sa.Column("title_jp", sa.String(), nullable=True),
            sa.Column("producer_jp", sa.String(), nullable=True),
            sa.Column("voicebank_jp", sa.String(), nullable=True),
            sa.Column("image_url", sa.String(), nullable=True),
            sa.Column("rank", sa.Integer(), nullable=True),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("link"),
        )
        op.create_index(op.f("ix_tracks_id"), "tracks", ["id"], unique=False)
        op.create_index(
            op.f("ix_tracks_producer"), "tracks", ["producer"], unique=False
        )
        op.create_index(op.f("ix_tracks_title"), "tracks", ["title"], unique=False)
        op.create_index(
            op.f("ix_tracks_voicebank"), "tracks", ["voicebank"], unique=False
        )
    else:
        # If table exists, check for columns
        columns = [c["name"] for c in inspector.get_columns("tracks")]
        if "producer_jp" not in columns:
            op.add_column(
                "tracks", sa.Column("producer_jp", sa.String(), nullable=True)
            )
        if "voicebank_jp" not in columns:
            op.add_column(
                "tracks", sa.Column("voicebank_jp", sa.String(), nullable=True)
            )

    if "update_logs" not in tables:
        op.create_table(
            "update_logs",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("updated_at", sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(op.f("ix_update_logs_id"), "update_logs", ["id"], unique=False)

    if "playlist_track_association" not in tables:
        op.create_table(
            "playlist_track_association",
            sa.Column("playlist_id", sa.Integer(), nullable=False),
            sa.Column("track_id", sa.Integer(), nullable=False),
            sa.Column("position", sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(
                ["playlist_id"],
                ["playlists.id"],
            ),
            sa.ForeignKeyConstraint(
                ["track_id"],
                ["tracks.id"],
            ),
            sa.PrimaryKeyConstraint("playlist_id", "track_id"),
        )

    if "ratings" not in tables:
        op.create_table(
            "ratings",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("track_id", sa.Integer(), nullable=False),
            sa.Column("rating", sa.Float(), nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.Column("updated_at", sa.DateTime(), nullable=False),
            sa.Column("notes", sa.String(), nullable=True),
            sa.ForeignKeyConstraint(
                ["track_id"],
                ["tracks.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(op.f("ix_ratings_id"), "ratings", ["id"], unique=False)
        op.create_index(op.f("ix_ratings_rating"), "ratings", ["rating"], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ratings_rating"), table_name="ratings")
    op.drop_index(op.f("ix_ratings_id"), table_name="ratings")
    op.drop_table("ratings")
    op.drop_table("playlist_track_association")
    op.drop_index(op.f("ix_update_logs_id"), table_name="update_logs")
    op.drop_table("update_logs")
    op.drop_index(op.f("ix_tracks_voicebank"), table_name="tracks")
    op.drop_index(op.f("ix_tracks_title"), table_name="tracks")
    op.drop_index(op.f("ix_tracks_producer"), table_name="tracks")
    op.drop_index(op.f("ix_tracks_id"), table_name="tracks")
    op.drop_table("tracks")
    op.drop_table("playlists")
    # ### end Alembic commands ###
